# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Katigoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Kausima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eidos', models.CharField(blank=True, max_length=50, null=True)),
                ('katigoria', models.CharField(blank=True, max_length=50, null=True)),
                ('upokatigoria', models.CharField(blank=True, max_length=50, null=True)),
                ('solines', models.FloatField(blank=True, null=True)),
                ('sortnumber', models.IntegerField(blank=True, null=True)),
                ('solines_m3_15', models.FloatField(blank=True, null=True)),
                ('solines_m3_thk', models.FloatField(blank=True, null=True)),
                ('katigoriaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tank_Measurement.Katigoria', verbose_name='katigoria')),
            ],
            options={
                'ordering': ('eidos',),
            },
        ),
        migrations.CreateModel(
            name='SubKatigoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('katigoriaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tank_Measurement.Katigoria', verbose_name='katigoria')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
