# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tank_Measurement', '0002_bulletstable_correctfactor_datakatastdex_dataminiaiodeltio_dataminiaiodeltio2append_dexamauthor_djan'),
    ]

    operations = [
        migrations.AddField(
            model_name='kausima',
            name='upokatigoriaid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tank_Measurement.SubKatigoria', verbose_name='SubKatigoria'),
        ),
    ]
