# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tank_Measurement', '0003_kausima_upokatigoriaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kausima',
            name='katigoria',
        ),
        migrations.RemoveField(
            model_name='kausima',
            name='upokatigoria',
        ),
    ]
