# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tank_Measurement', '0004_auto_20170909_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='KulindrikesDexamenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('pl_orofi', models.BooleanField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('ogkos', models.FloatField(blank=True, null=True)),
                ('geo_ups', models.FloatField(blank=True, null=True)),
                ('geo_diam', models.FloatField(blank=True, null=True)),
                ('ups_thal', models.FloatField(blank=True, null=True)),
                ('ogk_kon', models.FloatField(blank=True, null=True)),
                ('km_m_ups', models.FloatField(blank=True, null=True)),
                ('ups_ekx', models.FloatField(blank=True, null=True)),
                ('ups_kat', models.FloatField(blank=True, null=True)),
                ('m_ups_pl', models.FloatField(blank=True, null=True)),
                ('e_ups_tr_m', models.FloatField(blank=True, null=True)),
                ('ups_antl', models.FloatField(blank=True, null=True)),
                ('ups_pla', models.FloatField(blank=True, null=True)),
                ('m_ant_pos', models.FloatField(blank=True, null=True)),
                ('e_ups_for', models.FloatField(blank=True, null=True)),
                ('m_eis_pos', models.FloatField(blank=True, null=True)),
                ('the_pod', models.CharField(blank=True, max_length=1, null=True)),
                ('bar_oro', models.FloatField(blank=True, null=True)),
                ('per_p_kat1', models.FloatField(blank=True, null=True)),
                ('per_p_kat2', models.FloatField(blank=True, null=True)),
                ('per_p_ano1', models.FloatField(blank=True, null=True)),
                ('per_p_ano2', models.FloatField(blank=True, null=True)),
                ('d1y', models.FloatField(blank=True, null=True)),
                ('d1x', models.FloatField(blank=True, null=True)),
                ('d2y', models.FloatField(blank=True, null=True)),
                ('d2x', models.FloatField(blank=True, null=True)),
                ('d3y', models.FloatField(blank=True, null=True)),
                ('d3x', models.FloatField(blank=True, null=True)),
                ('d4y', models.FloatField(blank=True, null=True)),
                ('d4x', models.FloatField(blank=True, null=True)),
                ('d5y', models.FloatField(blank=True, null=True)),
                ('d5x', models.FloatField(blank=True, null=True)),
                ('d6y', models.FloatField(blank=True, null=True)),
                ('d6x', models.FloatField(blank=True, null=True)),
                ('d7y', models.FloatField(blank=True, null=True)),
                ('d7x', models.FloatField(blank=True, null=True)),
                ('d8y', models.FloatField(blank=True, null=True)),
                ('d8x', models.FloatField(blank=True, null=True)),
                ('d9y', models.FloatField(blank=True, null=True)),
                ('d9x', models.FloatField(blank=True, null=True)),
                ('d10y', models.FloatField(blank=True, null=True)),
                ('d10x', models.FloatField(blank=True, null=True)),
                ('d11y', models.FloatField(blank=True, null=True)),
                ('d11x', models.FloatField(blank=True, null=True)),
                ('d12y', models.FloatField(blank=True, null=True)),
                ('d12x', models.FloatField(blank=True, null=True)),
                ('monosi', models.BooleanField()),
                ('Kausimaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tank_Measurement.Kausima', verbose_name='Kausima')),
                ('katigoriaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tank_Measurement.Katigoria', verbose_name='katigoria')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='SfairikesDexamemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('ogkos', models.FloatField(blank=True, null=True)),
                ('a_cm', models.FloatField(blank=True, null=True)),
                ('b_cm', models.FloatField(blank=True, null=True)),
                ('yp_cm', models.FloatField(blank=True, null=True)),
                ('oa_lt', models.FloatField(blank=True, null=True)),
                ('bullets', models.BooleanField()),
                ('ogk_kon', models.FloatField(blank=True, null=True)),
                ('ups_kat', models.FloatField(blank=True, null=True)),
                ('katigoriaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tank_Measurement.Katigoria', verbose_name='katigoria')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
    ]
