# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-10 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tank_Measurement', '0005_kulindrikesdexamenes_sfairikesdexamemes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sftable0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sftprod', models.CharField(blank=True, max_length=50, null=True)),
                ('sftpre', models.FloatField(blank=True, null=True)),
                ('sftdens', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sftable',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='sftable',
            options={'ordering': ('id', 'sftprod')},
        ),
    ]
