# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-10 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tank_Measurement', '0007_auto_20170910_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sftable',
            name='sftprodid',
        ),
        migrations.DeleteModel(
            name='Sftable',
        ),
    ]
