# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-10 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tank_Measurement', '0008_auto_20170910_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShellSftable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sftpre', models.FloatField(blank=True, null=True)),
                ('sftdens', models.FloatField(blank=True, null=True)),
                ('sftprodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tank_Measurement.Kausima', verbose_name='Kausima')),
            ],
            options={
                'ordering': ('id', 'sftprodid'),
            },
        ),
    ]
